# Generated by Django 5.1.4 on 2025-01-05 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TermGroup",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Upraveno"),
                ),
                ("name", models.TextField(verbose_name="Název")),
            ],
            options={
                "verbose_name": "Skupina termínů",
                "verbose_name_plural": "Skupiny termínů",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Upraveno"),
                ),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "lang",
                    models.TextField(
                        choices=[("cz", "Czech"), ("en", "English")],
                        verbose_name="Jazyk",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vlastník",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="terms",
                        to="dictionary.termgroup",
                        verbose_name="Skupiny",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termín",
                "verbose_name_plural": "Termíny",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExerciseResult",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Upraveno"),
                ),
                (
                    "result",
                    models.TextField(
                        choices=[
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                            ("unknown", "Unknown"),
                        ],
                        verbose_name="Výsledek",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uživatel",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dictionary.term",
                        verbose_name="Termín",
                    ),
                ),
            ],
            options={
                "verbose_name": "Výsledek cvičení",
                "verbose_name_plural": "Výsledky cvičení",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="TermTranslation",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Upraveno"),
                ),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "lang",
                    models.TextField(
                        choices=[("cz", "Czech"), ("en", "English")],
                        verbose_name="Jazyk",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.term",
                        verbose_name="Termín",
                    ),
                ),
            ],
            options={
                "verbose_name": "Překlad",
                "verbose_name_plural": "Překlady",
                "ordering": ("created_at",),
            },
        ),
    ]
