# Generated by Django 5.1.4 on 2025-01-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termgroup",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Název"),
        ),
    ]
